// src/face_sorter/web/frontend/src/views/Training.vue
<template>
  <div class="training-view">
    <div class="view-header">
      <h1>🎯 Training</h1>
      <p class="subtitle">Detect faces and generate embeddings</p>
    </div>

    <!-- Training Form -->
    <div v-if="!operationStarted" class="training-form card">
      <h2 class="form-title">Training Configuration</h2>
      <form @submit.prevent="startTraining">
        <div class="form-grid grid-2">
          <div class="form-group">
            <label class="form-label">Source Directory</label>
            <input
              v-model="form.source_dir"
              type="text"
              class="form-input"
              placeholder="/path/to/images"
              required
            />
            <p class="form-help">Directory containing images to process</p>
          </div>

          <div class="form-group">
            <label class="form-label">No-Face Directory</label>
            <input
              v-model="form.noface_dir"
              type="text"
              class="form-input"
              placeholder="/path/to/noface"
            />
            <p class="form-help">Directory for images without faces</p>
          </div>

          <div class="form-group">
            <label class="form-label">Broken Images Directory</label>
            <input
              v-model="form.broken_dir"
              type="text"
              class="form-input"
              placeholder="/path/to/broken"
            />
            <p class="form-help">Directory for corrupted images</p>
          </div>

          <div class="form-group">
            <label class="form-label">Cache Directory</label>
            <input
              v-model="form.cache_dir"
              type="text"
              class="form-input"
              placeholder="/path/to/cache"
            />
            <p class="form-help">Directory for cached images</p>
          </div>
        </div>

        <div class="form-group">
          <label class="form-label">Duplicates Directory</label>
          <input
            v-model="form.duplicates_dir"
            type="text"
            class="form-input"
            placeholder="/path/to/duplicates"
          />
          <p class="form-help">Directory for duplicate images (will be skipped)</p>
        </div>

        <div class="form-actions">
          <button type="submit" class="btn btn-primary btn-large">
            <span class="btn-icon">🎯</span>
            <span>Start Training</span>
          </button>
        </div>
      </form>
    </div>

    <!-- Progress Display -->
    <div v-else class="progress-container">
      <ProgressBar
        operation-type="Training"
        :task-id="taskId"
        @cancel="handleCancel"
        @reset="handleReset"
      />
    </div>

    <!-- Info Section -->
    <div class="info-section card">
      <h3 class="info-title">About Training</h3>
      <div class="info-content">
        <p class="info-paragraph">
          <strong>Training</strong> performs face detection on your images using
          InsightFace and generates 512-dimensional face embeddings that can be used
          for recognition and clustering.
        </p>
        <ul class="info-list">
          <li>✅ Detects faces in images</li>
          <li>✅ Generates 512-dim embeddings</li>
          <li>✅ Extracts face metadata (age, gender, landmarks)</li>
          <li>✅ Moves images without faces to noface directory</li>
          <li>✅ Real-time progress tracking</li>
        </ul>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref } from "vue";
import ProgressBar from "../components/ProgressBar.vue";
import { apiService } from "../services/api";

const form = ref({
  source_dir: "",
  noface_dir: "",
  broken_dir: "",
  cache_dir: "",
  duplicates_dir: "",
});

const operationStarted = ref(false);
const taskId = ref("");
const loading = ref(false);

const startTraining = async () => {
  try {
    loading.value = true;
    const response = await apiService.startTraining(form.value);
    taskId.value = response.task_id;
    operationStarted.value = true;
  } catch (error) {
    console.error("Failed to start training:", error);
    alert("Failed to start training. Please check your configuration and try again.");
  } finally {
    loading.value = false;
  }
};

const handleCancel = () => {
  console.log("Training cancelled");
  operationStarted.value = false;
  taskId.value = "";
};

const handleReset = () => {
  operationStarted.value = false;
  taskId.value = "";
};
</script>

<style scoped>
.training-view {
  animation: fadeIn 0.5s ease;
}

@keyframes fadeIn {
  from {
    opacity: 0;
    transform: translateY(20px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

.view-header {
  margin-bottom: 30px;
}

.view-header h1 {
  font-size: 36px;
  font-weight: 700;
  color: var(--secondary-color);
  margin: 0 0 10px 0;
}

.subtitle {
  font-size: 18px;
  color: #666;
  margin: 0;
}

/* Form Styling */
.training-form {
  max-width: 900px;
  margin-bottom: 30px;
}

.form-title {
  font-size: 24px;
  font-weight: 600;
  color: var(--primary-color);
  margin: 0 0 24px 0;
  padding-bottom: 16px;
  border-bottom: 2px solid var(--primary-color);
}

.form-grid {
  margin-bottom: 24px;
}

.form-group {
  margin-bottom: 24px;
}

.form-label {
  display: block;
  font-size: 14px;
  font-weight: 600;
  color: var(--text-color);
  margin-bottom: 8px;
}

.form-input {
  width: 100%;
  padding: 12px 16px;
  border: 2px solid #e0e0e0;
  border-radius: 8px;
  font-size: 16px;
  font-family: inherit;
  transition: all 0.3s ease;
}

.form-input:focus {
  outline: none;
  border-color: var(--primary-color);
  box-shadow: 0 0 0 4px rgba(101, 123, 236, 0.1);
}

.form-help {
  font-size: 13px;
  color: #666;
  margin: 4px 0 0 0;
  line-height: 1.4;
}

.form-actions {
  display: flex;
  gap: 16px;
  margin-top: 32px;
}

.btn-large {
  padding: 16px 32px;
  font-size: 18px;
}

.btn-icon {
  margin-right: 8px;
  font-size: 20px;
}

/* Progress Container */
.progress-container {
  margin-bottom: 30px;
}

/* Info Section */
.info-section {
  max-width: 800px;
}

.info-title {
  font-size: 20px;
  font-weight: 600;
  color: var(--secondary-color);
  margin: 0 0 20px 0;
}

.info-content {
  line-height: 1.8;
}

.info-paragraph {
  margin-bottom: 20px;
}

.info-list {
  list-style: none;
  padding: 0;
}

.info-list li {
  padding: 8px 0;
  font-size: 16px;
  color: #333;
}

/* Responsive Design */
@media (max-width: 768px) {
  .form-grid {
    grid-template-columns: 1fr;
  }

  .form-actions {
    flex-direction: column;
  }

  .btn-large {
    width: 100%;
  }
}
</style>

// src/face_sorter/web/frontend/src/views/Training.jsx
import React, { useState } from 'react';
import './Training.css';
import ProgressBar from '../components/ProgressBar.jsx';
import FolderPicker from '../components/FolderPicker.jsx';
import { apiService } from '../services/api';
import websocketService from '../services/websocket';

function Training() {
  const [form, setForm] = useState({
    source_dir: '',
    noface_dir: '',
    broken_dir: '',
    cache_dir: '',
    duplicates_dir: '',
  });

  const [operationStarted, setOperationStarted] = useState(false);
  const [taskId, setTaskId] = useState('');
  const [loading, setLoading] = useState(false);
  
  // Progress state
  const [current, setCurrent] = useState(0);
  const [total, setTotal] = useState(0);
  const [currentStatus, setCurrentStatus] = useState('');
  const [currentItem, setCurrentItem] = useState('');
  const [logs, setLogs] = useState([]);

  const [showFolderPicker, setShowFolderPicker] = useState(false);
  const [currentField, setCurrentField] = useState('');

  const openFolderPicker = (field) => {
    setCurrentField(field);
    setShowFolderPicker(true);
  };

  const handleFolderSelect = (path) => {
    if (currentField) {
      setForm((prev) => ({ ...prev, [currentField]: path }));
    }
    setShowFolderPicker(false);
    setCurrentField('');
  };

  const handleFolderCancel = () => {
    setShowFolderPicker(false);
    setCurrentField('');
  };

  const handleChange = (e) => {
    const { name, value } = e.target;
    setForm((prev) => ({ ...prev, [name]: value }));
  };

  const handleMessage = (data) => {
    switch (data.type) {
      case 'progress':
        setCurrent(data.progress.current);
        setTotal(data.progress.total);
        setCurrentStatus(data.progress.status);
        setCurrentItem(data.progress.current_item || '');

        setLogs((prevLogs) => {
          const newLog = {
            time: new Date().toLocaleTimeString(),
            message: `${data.progress.status}: ${data.progress.current_item || ''}`,
          };
          const updatedLogs = [newLog, ...prevLogs];
          return updatedLogs.slice(0, 20);
        });
        break;

      case 'complete':
        setCurrentStatus('Complete');
        break;

      case 'error':
        window.alert(`Training failed: ${data.error.message || 'Unknown error'}`);
        break;
      default:
        break;
    }
  };

  const handleError = (wsError) => {
    console.error('[Training] WebSocket error:', wsError);
    window.alert('WebSocket connection error. Progress updates may not be available.');
  };

  const startTraining = async (e) => {
    e.preventDefault();
    try {
      setLoading(true);
      const response = await apiService.startTraining(form);
      setTaskId(response.task_id);
      setOperationStarted(true);

      websocketService.connect('training', response.task_id, handleMessage, handleError);
    } catch (error) {
      console.error('Failed to start training:', error);
      window.alert('Failed to start training. Please check your configuration and try again.');
    } finally {
      setLoading(false);
    }
  };

  const handleCancel = () => {
    websocketService.disconnect();
    setOperationStarted(false);
    setTaskId('');
    setCurrent(0);
    setTotal(0);
    setCurrentStatus('');
    setCurrentItem('');
    setLogs([]);
  };

  const handleReset = () => {
    websocketService.disconnect();
    setOperationStarted(false);
    setTaskId('');
    setCurrent(0);
    setTotal(0);
    setCurrentStatus('');
    setCurrentItem('');
    setLogs([]);
  };

  return (
    <div className="training-view">
      <div className="view-header">
        <h1>🎯 Training</h1>
        <p className="subtitle">Detect faces and generate embeddings</p>
      </div>

      {!operationStarted ? (
        <div className="training-form card">
          <h2 className="form-title">Training Configuration</h2>
          <form onSubmit={startTraining}>
            <div className="form-grid grid-2">
              <div className="form-group">
                <label className="form-label">Source Directory</label>
                <div className="input-with-browse">
                  <input
                    type="text"
                    name="source_dir"
                    value={form.source_dir}
                    onChange={handleChange}
                    className="form-input"
                    placeholder="/path/to/images"
                    required
                  />
                  <button
                    type="button"
                    className="browse-btn"
                    onClick={() => openFolderPicker('source_dir')}
                  >
                    📁 Browse
                  </button>
                </div>
                <p className="form-help">Directory containing images to process</p>
              </div>

              <div className="form-group">
                <label className="form-label">No-Face Directory</label>
                <div className="input-with-browse">
                  <input
                    type="text"
                    name="noface_dir"
                    value={form.noface_dir}
                    onChange={handleChange}
                    className="form-input"
                    placeholder="/path/to/noface"
                  />
                  <button
                    type="button"
                    className="browse-btn"
                    onClick={() => openFolderPicker('noface_dir')}
                  >
                    📁 Browse
                  </button>
                </div>
                <p className="form-help">Directory for images without faces</p>
              </div>

              <div className="form-group">
                <label className="form-label">Broken Images Directory</label>
                <div className="input-with-browse">
                  <input
                    type="text"
                    name="broken_dir"
                    value={form.broken_dir}
                    onChange={handleChange}
                    className="form-input"
                    placeholder="/path/to/broken"
                  />
                  <button
                    type="button"
                    className="browse-btn"
                    onClick={() => openFolderPicker('broken_dir')}
                  >
                    📁 Browse
                  </button>
                </div>
                <p className="form-help">Directory for corrupted images</p>
              </div>

              <div className="form-group">
                <label className="form-label">Cache Directory</label>
                <div className="input-with-browse">
                  <input
                    type="text"
                    name="cache_dir"
                    value={form.cache_dir}
                    onChange={handleChange}
                    className="form-input"
                    placeholder="/path/to/cache"
                  />
                  <button
                    type="button"
                    className="browse-btn"
                    onClick={() => openFolderPicker('cache_dir')}
                  >
                    📁 Browse
                  </button>
                </div>
                <p className="form-help">Directory for cached images</p>
              </div>
            </div>

            <div className="form-group">
              <label className="form-label">Duplicates Directory</label>
              <div className="input-with-browse">
                <input
                  type="text"
                  name="duplicates_dir"
                  value={form.duplicates_dir}
                  onChange={handleChange}
                  className="form-input"
                  placeholder="/path/to/duplicates"
                />
                <button
                  type="button"
                  className="browse-btn"
                  onClick={() => openFolderPicker('duplicates_dir')}
                >
                  📁 Browse
                </button>
              </div>
              <p className="form-help">Directory for duplicate images (will be skipped)</p>
            </div>

            <div className="form-actions">
              <button type="submit" className="btn btn-primary btn-large" disabled={loading}>
                <span className="btn-icon">🎯</span>
                <span>{loading ? 'Starting...' : 'Start Training'}</span>
              </button>
            </div>
          </form>
        </div>
      ) : (
        <div className="progress-section">
          <ProgressBar
            operationType="Training"
            taskId={taskId}
            current={current}
            total={total}
            currentStatus={currentStatus}
            currentItem={currentItem}
            logs={logs}
            idleText="Initializing..."
            onCancel={handleCancel}
            onReset={handleReset}
          />
        </div>
      )}

      <FolderPicker
        show={showFolderPicker}
        fieldType={currentField}
        initialPath={form[currentField] || ''}
        onSelect={handleFolderSelect}
        onCancel={handleFolderCancel}
      />

      <div className="info-section card">
        <h3 className="info-title">About Training</h3>
        <div className="info-content">
          <p className="info-paragraph">
            <strong>Training</strong> performs face detection on your images using
            InsightFace and generates 512-dimensional face embeddings that can be used
            for recognition and clustering.
          </p>
          <ul className="info-list">
            <li>✅ Detects faces in images</li>
            <li>✅ Generates 512-dim embeddings</li>
            <li>✅ Extracts face metadata (age, gender, landmarks)</li>
            <li>✅ Moves images without faces to noface directory</li>
            <li>✅ Real-time progress tracking</li>
          </ul>
        </div>
      </div>
    </div>
  );
}

export default Training;
